#!bin/bash
yum -y install git
git clone https://github.com/Hoangdinh85/NTI-300
git config --global user.name Hoangdinh85
git config --global user.email hdinh47056@gmail.com
git config --global core.editor vim
cd NTI-300
[root@apache-automated NTI-300]# git config user.name
Hoangdinh85
[root@apache-automated NTI-300]# git config user.email
hdinh47056@gmail.com
[root@apache-automated NTI-300]# git config core.editor 
vim
