#!/bin/bash


#sudo su into root
#install the python package
yum install python-pip

#install virtualenv using pip
pip install virtualenv

#upgrade pip to current version
pip install --upgrade pip


#make a directory call /opt/django
mkdir /opt/django
cd /opt/django

#python 
yum install python36
virtualenv -p python36 django
source django/bin/activate
pip install django
#django-admin --version #python 2.1.2


##start project1
django-admin startproject project1

##Change the user for django and porject1 to username:hdinh47056
chown -R hdinh47056 django
chown -R hdinh47056 project1

##Start the django test server 
source /opt/django/django/bin/activate
/opt/django/project1/manage.py runserver 0.0.0.0:8000&


##make the firewall rule in google cloud
##click on the ip address on instance, then remove the "s" in HTTP and add 8000 to the ip address


##Allow ip address
grep -iR ALLOWED /opt/django/project1
vim /opt/django/project1/project1/settings.py

sudo -u hdinh47056  sh -c " source /opt/django/django/bin/activate && python manage.py runserver 0.0.0.0:8000&"
sed "s/ALLOWED_HOSTS = []/ALLOWED_HOSTS = ['35.243.199.140']/g"
